# Generated by Django 4.2.8 on 2023-12-24 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogs',
            old_name='descriptions',
            new_name='description',
        ),
    ]
