# Generated by Django 4.2.8 on 2023-12-24 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_descriptions_blogs_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='image',
            field=models.ImageField(upload_to='main/blogs/image'),
        ),
    ]
